spring:
  application:
    name: csvapp
logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%10.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%-20.-20M){blue} %clr(:){faint} %m%n%wEx}}"
    level:
        org.springframework.security: DEBUG
tomcat:
  port: 8080
data:
  file: data.csv